/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ProductCategory = IDL.Variant({
  'occasionPackages' : IDL.Null,
  'haar' : IDL.Null,
  'thaliSets' : IDL.Null,
  'books' : IDL.Null,
  'pujaEssentials' : IDL.Null,
  'flowers' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const OrderStatus = IDL.Variant({
  'shipped' : IDL.Null,
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'processed' : IDL.Null,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'inStock' : IDL.Bool,
  'name' : IDL.Text,
  'unit' : IDL.Text,
  'occasionTag' : IDL.Opt(IDL.Text),
  'description' : IDL.Text,
  'category' : ProductCategory,
  'price' : IDL.Nat,
});
export const OrderItem = IDL.Record({
  'quantity' : IDL.Nat,
  'product' : Product,
});
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'status' : OrderStatus,
  'total' : IDL.Nat,
  'user' : IDL.Principal,
  'address' : IDL.Text,
  'phone' : IDL.Text,
  'items' : IDL.Vec(OrderItem),
});
export const PrasadOrderStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'dispatched' : IDL.Null,
  'delivered' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const PrasadOrder = IDL.Record({
  'id' : IDL.Nat,
  'status' : PrasadOrderStatus,
  'deliveryAddress' : IDL.Text,
  'userId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'instructions' : IDL.Text,
  'templeName' : IDL.Text,
  'pricePerBox' : IDL.Nat,
  'quantity' : IDL.Nat,
  'templeId' : IDL.Nat,
  'contactNumber' : IDL.Text,
  'prasadItemName' : IDL.Text,
  'totalPrice' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const CartItem = IDL.Record({
  'productId' : IDL.Nat,
  'quantity' : IDL.Nat,
});
export const PanditAvailability = IDL.Record({
  'available' : IDL.Bool,
  'panditId' : IDL.Text,
});
export const Review = IDL.Record({
  'productId' : IDL.Nat,
  'comment' : IDL.Text,
  'rating' : IDL.Nat,
  'reviewer' : IDL.Principal,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addProduct' : IDL.Func(
      [
        IDL.Text,
        ProductCategory,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Bool,
        IDL.Opt(IDL.Text),
      ],
      [],
      [],
    ),
  'addReview' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [], []),
  'addToCart' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bookPrasad' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
  'cancelPrasadOrder' : IDL.Func([IDL.Nat], [], []),
  'claimFirstAdmin' : IDL.Func([], [], []),
  'clearCart' : IDL.Func([], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'ensureCallerIsUser' : IDL.Func([], [], []),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getAllPrasadOrders' : IDL.Func([], [IDL.Vec(PrasadOrder)], ['query']),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
  'getMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getPanditAvailabilities' : IDL.Func(
      [],
      [IDL.Vec(PanditAvailability)],
      ['query'],
    ),
  'getPrasadOrders' : IDL.Func([], [IDL.Vec(PrasadOrder)], ['query']),
  'getProductReviews' : IDL.Func([IDL.Nat], [IDL.Vec(Review)], ['query']),
  'getProductsByCategory' : IDL.Func(
      [ProductCategory],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isAdminAssigned' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'placeOrder' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'removeFromCart' : IDL.Func([IDL.Nat], [], []),
  'removeProduct' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setPanditAvailability' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
  'updatePrasadOrderStatus' : IDL.Func([IDL.Nat, PrasadOrderStatus], [], []),
  'updateProduct' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        ProductCategory,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Bool,
        IDL.Opt(IDL.Text),
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ProductCategory = IDL.Variant({
    'occasionPackages' : IDL.Null,
    'haar' : IDL.Null,
    'thaliSets' : IDL.Null,
    'books' : IDL.Null,
    'pujaEssentials' : IDL.Null,
    'flowers' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const OrderStatus = IDL.Variant({
    'shipped' : IDL.Null,
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'processed' : IDL.Null,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'inStock' : IDL.Bool,
    'name' : IDL.Text,
    'unit' : IDL.Text,
    'occasionTag' : IDL.Opt(IDL.Text),
    'description' : IDL.Text,
    'category' : ProductCategory,
    'price' : IDL.Nat,
  });
  const OrderItem = IDL.Record({ 'quantity' : IDL.Nat, 'product' : Product });
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'status' : OrderStatus,
    'total' : IDL.Nat,
    'user' : IDL.Principal,
    'address' : IDL.Text,
    'phone' : IDL.Text,
    'items' : IDL.Vec(OrderItem),
  });
  const PrasadOrderStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'dispatched' : IDL.Null,
    'delivered' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const PrasadOrder = IDL.Record({
    'id' : IDL.Nat,
    'status' : PrasadOrderStatus,
    'deliveryAddress' : IDL.Text,
    'userId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'instructions' : IDL.Text,
    'templeName' : IDL.Text,
    'pricePerBox' : IDL.Nat,
    'quantity' : IDL.Nat,
    'templeId' : IDL.Nat,
    'contactNumber' : IDL.Text,
    'prasadItemName' : IDL.Text,
    'totalPrice' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const CartItem = IDL.Record({ 'productId' : IDL.Nat, 'quantity' : IDL.Nat });
  const PanditAvailability = IDL.Record({
    'available' : IDL.Bool,
    'panditId' : IDL.Text,
  });
  const Review = IDL.Record({
    'productId' : IDL.Nat,
    'comment' : IDL.Text,
    'rating' : IDL.Nat,
    'reviewer' : IDL.Principal,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addProduct' : IDL.Func(
        [
          IDL.Text,
          ProductCategory,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Bool,
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
    'addReview' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [], []),
    'addToCart' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bookPrasad' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
    'cancelPrasadOrder' : IDL.Func([IDL.Nat], [], []),
    'claimFirstAdmin' : IDL.Func([], [], []),
    'clearCart' : IDL.Func([], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'ensureCallerIsUser' : IDL.Func([], [], []),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getAllPrasadOrders' : IDL.Func([], [IDL.Vec(PrasadOrder)], ['query']),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
    'getMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getPanditAvailabilities' : IDL.Func(
        [],
        [IDL.Vec(PanditAvailability)],
        ['query'],
      ),
    'getPrasadOrders' : IDL.Func([], [IDL.Vec(PrasadOrder)], ['query']),
    'getProductReviews' : IDL.Func([IDL.Nat], [IDL.Vec(Review)], ['query']),
    'getProductsByCategory' : IDL.Func(
        [ProductCategory],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isAdminAssigned' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'placeOrder' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'removeFromCart' : IDL.Func([IDL.Nat], [], []),
    'removeProduct' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setPanditAvailability' : IDL.Func([IDL.Text, IDL.Bool], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
    'updatePrasadOrderStatus' : IDL.Func([IDL.Nat, PrasadOrderStatus], [], []),
    'updateProduct' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          ProductCategory,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Bool,
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };