/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CartItem { 'productId' : bigint, 'quantity' : bigint }
export interface Order {
  'id' : bigint,
  'customerName' : string,
  'status' : OrderStatus,
  'total' : bigint,
  'user' : Principal,
  'address' : string,
  'phone' : string,
  'items' : Array<OrderItem>,
}
export interface OrderItem { 'quantity' : bigint, 'product' : Product }
export type OrderStatus = { 'shipped' : null } |
  { 'cancelled' : null } |
  { 'pending' : null } |
  { 'processed' : null };
export interface PanditAvailability {
  'available' : boolean,
  'panditId' : string,
}
export interface Product {
  'id' : bigint,
  'inStock' : boolean,
  'name' : string,
  'unit' : string,
  'occasionTag' : [] | [string],
  'description' : string,
  'category' : ProductCategory,
  'price' : bigint,
}
export type ProductCategory = { 'occasionPackages' : null } |
  { 'haar' : null } |
  { 'thaliSets' : null } |
  { 'books' : null } |
  { 'pujaEssentials' : null } |
  { 'flowers' : null };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addProduct' : ActorMethod<
    [string, ProductCategory, string, bigint, string, boolean, [] | [string]],
    undefined
  >,
  'addToCart' : ActorMethod<[bigint, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearCart' : ActorMethod<[], undefined>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCart' : ActorMethod<[], Array<CartItem>>,
  'getMyOrders' : ActorMethod<[], Array<Order>>,
  'getPanditAvailabilities' : ActorMethod<[], Array<PanditAvailability>>,
  'getProductsByCategory' : ActorMethod<[ProductCategory], Array<Product>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'placeOrder' : ActorMethod<[string, string, string], undefined>,
  'removeFromCart' : ActorMethod<[bigint], undefined>,
  'removeProduct' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setPanditAvailability' : ActorMethod<[string, boolean], undefined>,
  'updateOrderStatus' : ActorMethod<[bigint, OrderStatus], undefined>,
  'updateProduct' : ActorMethod<
    [
      bigint,
      string,
      ProductCategory,
      string,
      bigint,
      string,
      boolean,
      [] | [string],
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];