/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CartItem { 'productId' : bigint, 'quantity' : bigint }
export interface Order {
  'id' : bigint,
  'customerName' : string,
  'status' : OrderStatus,
  'total' : bigint,
  'user' : Principal,
  'address' : string,
  'phone' : string,
  'items' : Array<OrderItem>,
}
export interface OrderItem { 'quantity' : bigint, 'product' : Product }
export type OrderStatus = { 'shipped' : null } |
  { 'cancelled' : null } |
  { 'pending' : null } |
  { 'processed' : null };
export interface PanditAvailability {
  'available' : boolean,
  'panditId' : string,
}
export interface PrasadOrder {
  'id' : bigint,
  'status' : PrasadOrderStatus,
  'deliveryAddress' : string,
  'userId' : Principal,
  'createdAt' : bigint,
  'instructions' : string,
  'templeName' : string,
  'pricePerBox' : bigint,
  'quantity' : bigint,
  'templeId' : bigint,
  'contactNumber' : string,
  'prasadItemName' : string,
  'totalPrice' : bigint,
}
export type PrasadOrderStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'dispatched' : null } |
  { 'delivered' : null } |
  { 'confirmed' : null };
export interface Product {
  'id' : bigint,
  'inStock' : boolean,
  'name' : string,
  'unit' : string,
  'occasionTag' : [] | [string],
  'description' : string,
  'category' : ProductCategory,
  'price' : bigint,
}
export type ProductCategory = { 'occasionPackages' : null } |
  { 'haar' : null } |
  { 'thaliSets' : null } |
  { 'books' : null } |
  { 'pujaEssentials' : null } |
  { 'flowers' : null };
export interface Review {
  'productId' : bigint,
  'comment' : string,
  'rating' : bigint,
  'reviewer' : Principal,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addProduct' : ActorMethod<
    [string, ProductCategory, string, bigint, string, boolean, [] | [string]],
    undefined
  >,
  'addReview' : ActorMethod<[bigint, bigint, string], undefined>,
  'addToCart' : ActorMethod<[bigint, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bookPrasad' : ActorMethod<
    [bigint, string, string, bigint, bigint, string, string, string],
    undefined
  >,
  'cancelPrasadOrder' : ActorMethod<[bigint], undefined>,
  'claimFirstAdmin' : ActorMethod<[], undefined>,
  'clearCart' : ActorMethod<[], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'ensureCallerIsUser' : ActorMethod<[], undefined>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAllPrasadOrders' : ActorMethod<[], Array<PrasadOrder>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCart' : ActorMethod<[], Array<CartItem>>,
  'getMyOrders' : ActorMethod<[], Array<Order>>,
  'getPanditAvailabilities' : ActorMethod<[], Array<PanditAvailability>>,
  'getPrasadOrders' : ActorMethod<[], Array<PrasadOrder>>,
  'getProductReviews' : ActorMethod<[bigint], Array<Review>>,
  'getProductsByCategory' : ActorMethod<[ProductCategory], Array<Product>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isAdminAssigned' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'placeOrder' : ActorMethod<[string, string, string], undefined>,
  'removeFromCart' : ActorMethod<[bigint], undefined>,
  'removeProduct' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setPanditAvailability' : ActorMethod<[string, boolean], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateOrderStatus' : ActorMethod<[bigint, OrderStatus], undefined>,
  'updatePrasadOrderStatus' : ActorMethod<
    [bigint, PrasadOrderStatus],
    undefined
  >,
  'updateProduct' : ActorMethod<
    [
      bigint,
      string,
      ProductCategory,
      string,
      bigint,
      string,
      boolean,
      [] | [string],
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];